### ISSUE TITLE
Dashboard MVP

### ISSUE THREAD

**Issue by jon-bell** [classee-cloud/dashboard#2]
Basic React application that integrates with our SSO, has a reasonable, responsive layout with header on top and menu on left. Uses Chakra-UI. Supports log-in and log-out, shows the user's name in the header

**Comment by rajatkeshri** [comment]
Commit - [b26216e](https://github.com/classee-cloud/dashboard/pull/3/commits/b26216e8c91b65bef71a7be2c152eb2e238510bf)
